{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bird-services.fullname" . }}
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "bird-services.fullname" $ }}-{{ .service | default "unknown-service" }}
                port:
                  number: {{ if eq .service "bird-api" }}{{ $.Values.birdAPI.service.port }}{{ else if eq .service "bird-image-service" }}{{ $.Values.birdImageService.service.port }}{{ else }} 80 {{ end }}
          {{- end }}
    {{- end }}
{{- end }}
