# templates/bird-image-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-image-service
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-image-service
spec:
  {{- if not .Values.birdImageService.autoscaling.enabled }}
  replicas: {{ .Values.birdImageService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bird-services.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bird-image-service
  template:
    metadata:
      labels:
        {{- include "bird-services.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bird-image-service
    spec:
      serviceAccountName: {{ include "bird-services.fullname" . }}-bird-image-service
      securityContext:
        {{- toYaml .Values.birdImageService.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bird-image-service
          image: "{{ .Values.birdImageService.image.repository }}:{{ .Values.birdImageService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.birdImageService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.birdImageService.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.birdImageService.resources | nindent 12 }}