# templates/bird-image-service/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-image-service
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-image-service
spec:
  minAvailable: {{ .Values.birdImageService.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "bird-services.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bird-image-service