# templates/bird-image-service/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-image-service
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-image-service