# templates/bird-api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-api
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api
spec:
  {{- if not .Values.birdAPI.autoscaling.enabled }}
  replicas: {{ .Values.birdAPI.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bird-services.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bird-api
  template:
    metadata:
      labels:
        {{- include "bird-services.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bird-api
    spec:
      serviceAccountName: {{ include "bird-services.fullname" . }}-bird-api
      securityContext:
        {{- toYaml .Values.birdAPI.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-bird-api
          image: "{{ .Values.birdAPI.image.repository }}:{{ .Values.birdAPI.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.birdAPI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.birdAPI.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.birdAPI.resources | nindent 12 }}