# templates/bird-api/hpa.yaml
{{- if .Values.birdAPI.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-api
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bird-services.fullname" . }}-bird-api
  minReplicas: {{ .Values.birdAPI.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.birdAPI.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.birdAPI.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
