{{- if .Values.birdAPI.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-api
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api
spec:
  podSelector:
    matchLabels:
      {{- include "bird-services.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bird-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "bird-services.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.birdAPI.service.port }}
    {{- if .Values.birdAPI.networkPolicy.ingressController }}
    - from:
        - namespaceSelector:
            matchLabels:
              {{- .Values.birdAPI.networkPolicy.ingressController.namespaceSelector | toYaml | nindent 14 }}
          podSelector:
            matchLabels:
              {{- .Values.birdAPI.networkPolicy.ingressController.podSelector | toYaml | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.birdAPI.service.port }}
    {{- end }}
{{- end }}