# templates/bird-api/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-api
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api