apiVersion: v1
kind: Service
metadata:
  name: {{ include "bird-services.fullname" . }}-bird-api
  labels:
    {{- include "bird-services.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api
  {{- with .Values.birdAPI.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.birdAPI.service.type }}
  ports:
    - port: {{ .Values.birdAPI.service.port }}
      targetPort: {{ .Values.birdAPI.service.port }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.birdAPI.service.type "NodePort") .Values.birdAPI.service.nodePort }}
      nodePort: {{ .Values.birdAPI.service.nodePort }}
      {{- end }}
  selector:
    {{- include "bird-services.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api