# values.yaml
global:
  environment: bird-challenge

birdAPI:
  enabled: true
  replicaCount: 2
  image:
    repository: hediabed/bird-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4201
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  networkPolicy:
    enabled: false

birdImageService:
  enabled: true
  replicaCount: 2
  image:
    repository: hediabed/bird-image-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4200
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  networkPolicy:
    enabled: false

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:590184049425:certificate/eaacb3b5-91d8-4740-a03f-221fe053b84d # To Be Modified
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":443}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: alb
  hosts:
    - host: service1.590184049425.realhandsonlabs.net # To be modified
      paths:
        - path: /api
          pathType: Prefix
          service: bird-api
        - path: /image
          pathType: Prefix
          service: bird-image-service
