global:
  environment: bird-challenge

birdAPI:
  enabled: true
  replicaCount: 2
  image:
    repository: zoeid/bird-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4201
    annotations: {}
    # nodePort: 30201  # Uncomment and set this if using NodePort
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  networkPolicy:
    enabled: false
    ingressController:
      namespaceSelector:
        name: ingress-nginx
      podSelector:
        app.kubernetes.io/name: ingress-nginx

birdImageService:
  enabled: true
  replicaCount: 2
  image:
    repository: zoeid/bird-image-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4200
    annotations: {}
    # nodePort: 30200  # Uncomment and set this if using NodePort
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  networkPolicy:
    enabled: false
    ingressController:
      namespaceSelector:
        name: ingress-nginx
      podSelector:
        app.kubernetes.io/name: ingress-nginx

ingress:
  enabled: true
  className: alb
  annotations: {}
  hosts: []
